app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, TextAreaField, SelectField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed
from app.models import City, Category

#form for post
class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    price = IntegerField('Price', validators=[DataRequired()])
    city = SelectField('City', choices=[(city.value) for city in City], validators=[DataRequired()])
    picture = FileField('Instrument Picture', validators=[FileAllowed(['jpg', 'png'])])
    category = SelectField('Category', choices=[(category.value) for category in Category], validators=[DataRequired()])
    submit = SubmitField('post')

app/chats/routes.py
from flask import Blueprint, render_template, redirect, url_for, abort
from flask_login import login_required, current_user
from app.models import Chat, Message, Post
from datetime import datetime, timedelta
from sqlalchemy import or_
from app import db

messages = Blueprint('messages', __name__)

@messages.route('/create_chat/<int:author_id>', methods=['GET', 'POST'])
@login_required
def create_chat(author_id):
    """
    Route to create a chat between the current user and another user (author of a post).
    """
    # Get the current user's ID
    current_user_id = current_user.id
    
    # Ensure the author exists
    author = Post.query.get_or_404(author_id)

    # Sort the IDs to create a unique chat ID
    user1_id, user2_id = sorted([str(current_user_id), str(author_id)])
    chat_id = f"{user1_id}_{user2_id}"

    # Create an initial message
    initial_message_content = f"I am interested in your post: {author.title}, let's chat"
    initial_message = Message(chat_id=chat_id, user_id=current_user_id, content=initial_message_content, timestamp=datetime.utcnow())
    db.session.add(initial_message)
    db.session.commit()
    
    # Check if the chat already exists, if not, create it
    chat = Chat.query.filter_by(id=chat_id).first()
    if not chat:
        chat = Chat(id=chat_id, user1_id=user1_id, user2_id=user2_id)
        db.session.add(chat)
        db.session.commit()

    # Redirect to the chat page
    return redirect(url_for('messages.chats', chat_id=chat_id))

@messages.route('/chats', methods=['GET', 'POST'])
@login_required
def chats():
    """
    Route to display all chats of the current user.
    """
    # Retrieve all chats where the current user is a participant
    chats = Chat.query.filter(or_(Chat.user1_id == current_user.id, Chat.user2_id == current_user.id)).all()

    # Prepare a dictionary to store messages for each chat
    chat_messages = {}
    for chat in chats:
        # Retrieve messages associated with the chat
        messages = Message.query.filter_by(chat_id=chat.id).all()
        # Store messages in the dictionary with chat_id as key
        chat_messages[chat.id] = messages
    
    # Pass the current date and time to the template
    current_datetime = datetime.now()
    timedelta_class = timedelta
    current_user_id = current_user.id


    # Render the template with the user's chats and associated messages
    return render_template('message.html', chats=chats, chat_messages=chat_messages, current_datetime=current_datetime, timedelta_class=timedelta_class, current_user_id=current_user_id)

@messages.route('/chat/<chat_id>', methods=['GET'])
@login_required
def chat(chat_id):
    """
    Route to display a specific chat and its messages.
    """
    # Retrieve the chat based on the chat ID
    chat = Chat.query.get_or_404(chat_id)
    
    # Check if the current user is one of the participants in the chat
    if current_user.id not in [chat.user1_id, chat.user2_id]:
        abort(403)  # Access forbidden
    else:
        # Fetch messages related to the chat
        messages = Message.query.filter_by(chat_id=chat_id).all()
    
    # Render the chat template with messages
    return render_template('message.html', chat=chat, messages=messages)

app/main/routes.py
from flask import Blueprint, render_template, request
from app.models import Post, Review, Expirence
from flask_login import login_required

# Create a blueprint named 'main'
main = Blueprint('main', __name__)

@main.route("/")
@main.route("/index")
def index():
    """
    Route for the home page.
    Displays a list of recent posts and experiences.
    """
    # Query the database for the 10 most recent posts
    posts = Post.query.order_by(Post.date_posted.desc()).limit(10).all()
    # Query the database for the 10 highest-rated experiences
    experiences = Expirence.query.filter(Expirence.star_rating >= 4).order_by(Expirence.star_rating.desc()).limit(10).all()
    # Render the index.html template with the posts and experiences
    return render_template('index.html', posts=posts, experiences=experiences)

@main.route("/about")
def about():
    """
    Route for the about page.
    """
    # Render the about.html template
    return render_template('about.html', title='About Us')


@main.route("/home")
@login_required
def home():
    """
    Route for the user's home page.
    Displays the user's posts, reviews, and review counts.
    """
    # Get the current page number from the request arguments
    page = request.args.get('page', 1, type=int)
    # Query the database for paginated posts
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5)
    # Query the database for all reviews
    reviews = Review.query.all()
    # Dictionary to store review counts for each post
    post_review_counts = {}
    # Calculate the number of reviews for each post
    for post in posts:
        review_count = Review.query.filter_by(author_id=post.author.id).count()
        post_review_counts[post.id] = review_count
    # Render the home.html template with posts, reviews, and review counts
    return render_template('home.html', posts=posts, reviews=reviews, post_review_counts=post_review_counts, page=page)

app/posts/routes.py
from flask import Blueprint, render_template, redirect, abort, request, flash, url_for
from flask_login import login_required, current_user
from .forms import PostForm
from app.models import Post
from app import db
from .utils import post_picture

# Create a blueprint named 'posts'
posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    """
    Route to create a new post.
    Users can create new posts by filling out the post form.
    """
    # Create an instance of the PostForm
    form = PostForm()
    picture_file = None
    if form.validate_on_submit():
        # If the form is submitted and validated
        if form.picture.data:
            # Save the uploaded picture and get the filename
            picture_file = post_picture(form.picture.data)
            # Create a new Post object with the form data and the current user as the author
            post = Post(
                title=form.title.data,
                description=form.description.data,
                price=form.price.data,
                city=form.city.data,
                category=form.category.data,
                image_file=picture_file,
                author=current_user
            )
        # Add the post to the database and commit the session
        db.session.add(post)
        db.session.commit()
        # Flash a success message and redirect the user to the home page
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    # Render the create_post.html template with the form
    return render_template('create_post.html', title='New Post', form=form, image_file=picture_file, legend='New Post')

@posts.route('/post/<int:post_id>')
@login_required
def post(post_id):
    """
    Route to view a specific post.
    Users can view the details of a post by its ID.
    """
    # Get the post with the specified ID from the database
    post = Post.query.get_or_404(post_id)
     # Render the post.html template with the post data
    return render_template('post.html', title=post.title, post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    """
    Route to update an existing post.
    Users can update their own posts by filling out the update form.
    """
    # Get the post with the specified ID from the database
    post = Post.query.get_or_404(post_id)
    # Check if the current user is the author of the post
    if post.author != current_user:
        abort(403)  # HTTP 403 Forbidden

    form = PostForm()
    picture_file = None
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = post_picture(form.picture.data)
            post.image_file = picture_file
        # Update the post with the new data from the form
        post.title = form.title.data
        post.description = form.description.data
        post.price = form.price.data
        post.city = form.city.data
        post.category = form.category.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('main.home'))
    
    elif request.method == 'GET':
        # Pre-fill the form fields with the current post data
        form.title.data = post.title
        form.description.data = post.description
        form.price.data = int(post.price)
        form.city.data = post.city
        form.category.data = post.category
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post', image_file=picture_file)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    """
    Route to delete an existing post.
    Users can delete their own posts.
    """
    # Get the post with the specified ID from the database
    post = Post.query.get_or_404(post_id)
    # Check if the current user is the author of the post
    if post.author != current_user:
        abort(403)  # HTTP 403 Forbidden
    db.session.delete(post)
    db.session.commit()
    flash('Your Post has been deleted!', 'success')
    return redirect(url_for('main.home'))

app/users/routes.py
from flask import Blueprint, redirect, render_template, url_for, flash, request
from flask_login import login_required, current_user, login_user, logout_user
from app import db, bcrypt
from .forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from .utils import save_picture, send_reset_email
from app.models import User, Post, Review

# Import the Blueprint class to create a blueprint for user-related routes
users = Blueprint('users', __name__)

@users.route("/signup", methods=['GET', 'POST'])
def register():
    """
    Route to handle user registration.
    If the user is already authenticated, they are redirected to the home page.
    If the registration form is submitted and validated, the user is registered and redirected to the login page.
    """
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        # Hash the password and create a new user
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(first_name=form.first_name.data, last_name=form.last_name.data, email=form.email.data, phone_number=form.phone_number.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Your account has been created! You are now able to log in", 'success')
        return redirect(url_for('users.login'))
    return render_template('signup.html', form=form, title='Signup')

@users.route("/login", methods=['GET', 'POST'])
def login():
    """
    Route to handle user login.
    If the user is already authenticated, they are redirected to the home page.
    If the login form is submitted and validated, the user is logged in and redirected to the next page or home page.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', form=form, title='Login')

@users.route('/logout')
def logout():
    """
    Route to handle user logout.
    The user is logged out and redirected to the home page.
    """
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    """
    Route to handle updating user account details.
    If the form is submitted and validated, the user's details are updated.
    If the request method is GET, the form is populated with the current user's details.
    """
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.city = form.city.data
        current_user.verification_number = form.verification_number.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.city.data = current_user.city
        form.verification_number.data = current_user.verification_number
    image_file = url_for('static', filename='images/profile_pic/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/posts/<int:user_id>")
@login_required
def user_posts(user_id):
    """
    Route to display posts of a specific user.
    The posts are paginated and the total number of reviews for each post is calculated.
    """
    page = request.args.get('page', 1, type=int)
    user = User.query.get_or_404(user_id)
    posts = Post.query.filter_by(user_id=user.id).order_by(Post.date_posted.desc()).paginate(per_page=5)
    reviews = Review.query.all()
    post_review_counts = {}

    for post in posts:
        review_count = Review.query.filter_by(author_id=post.author.id).count()
        post_review_counts[post.id] = review_count
    return render_template('user_post.html', posts=posts, reviews=reviews, post_review_counts=post_review_counts, page=page, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    """
    Route to handle password reset request.
    If the form is submitted and validated, an email is sent to the user with instructions to reset their password.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An Email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('main.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    """
    Route to handle resetting the password using a token.
    If the token is invalid or expired, the user is redirected to the reset request page.
    If the form is submitted and validated, the user's password is updated.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f"Your Password has been updated! You are now able to log in", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

app/templates/405.html
{% extends 'base.html' %}
{% block content%}
    <div class="error-container">
        <div class="error-content">
            <h2>405</h2>
            <h4>Method Not Allowed</h4>
            <p>The method is not allowed for the requested URL. You may have mistakenly typed the address or the page may have been moved.</p>
            <a href="{{ url_for('main.index') }}">Back to Index</a>
        </div>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
    <link rel="icon" href="{{ url_for('static', filename='images/website_pic/package/logo.png')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    
    {% if title %}
        <title>InstruLend - {{ title }} </title>
    {{ else }}
        <title>InstruLend</title>
    {% endif %}
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->
</head>
<body>
    <header class="header">
        <a href="{{ url_for('main.index') }}" class="brand"><img src="{{ url_for('static', filename='images/website_pic/package/logo.png') }}">InstruLend</a>
        <div class="menu-btn"><span><i class="ri-menu-line"></i></span></div>
        <div class="navigation">
            <div class="navigation-items">
              {% if current_user.is_authenticated %}
                <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-link active" aria-current="page" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-link active" aria-current="page" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-link" href="{{ url_for('users.register') }}">SignUp</a>
              {% endif %}
            </div>
        </div>
    </header>
    <section>
      {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert message posts-display alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      {% block content %}{% endblock %}
    </section>
    <footer class="footer">
      <div class="footer_bar">
          Copyright &copy; 2024 InstruLend. All rights reserved.
      </div>
  </footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://unpkg.com/scrollreveal"></script>
  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  <script src="{{ url_for('static', filename='scripts/app.js') }}"></script>
  <script src="{{ url_for('static', filename='scripts/main.js') }}"></script>
  <script src="{{ url_for('static', filename='scripts/socketio.js') }}"></script>
  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script> -->
</body>
</html>

app/templates/base1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
    <link rel="icon" href="{{ url_for('static', filename='images/website_pic/package/logo.png')}}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    
    {% if title %}
        <title>InstruLend - {{ title }} </title>
    {{ else }}
        <title>InstruLend</title>
    {% endif %}
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->
</head>
<body>
    <header>
        <a href="{{ url_for('main.index') }}" class="brand"><img src="{{ url_for('static', filename='images/website_pic/package/logo.png') }}">InstruLend</a>
        <div class="menu-btn"><span><i class="ri-menu-line"></i></span></div>
        <div class="navigation">
            <div class="navigation-items">
              {% if current_user.is_authenticated %}
                <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-link active" aria-current="page" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-link active" aria-current="page" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-link" href="{{ url_for('users.register') }}">SignUp</a>
              {% endif %}
            </div>
        </div>
    </header>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert message posts-display alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      {% block content %}{% endblock %}
    </div>
    <footer class="footer">
      <div class="footer_bar">
          Copyright &copy; 2024 InstruLend. All rights reserved.
      </div>
  </footer>
  <script src="https://unpkg.com/scrollreveal"></script>
  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  <script src="{{ url_for('static', filename='scripts/app.js') }}"></script>
  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script> -->
</body>
</html>

app/templates/post.html
{% extends 'base.html' %}
{% block content %}
<section class="section-form">
  <div class="post-container">
    <div class="post-author">
      <img src="{{ url_for('static', filename='images/profile_pic/' + post.author.image_file) }}" alt="">
      <div>
        <h1>{{ post.author.first_name }} {{ post.author.last_name }}</h1>
        <small>{{ post.city }}, {{ post.country }}</small>
        <small>{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      </div>
    </div>
    <h1>{{ post.title }}  Price: {{ post.price }}<span>category: {{ post.category }}</span></h1>
    <p>{{ post.description }}</p>
    <img src="{{ url_for('static', filename='images/post_pic/' + post.image_file) }}" width="100%">
    <div class="post-activity">
      {% if post.author == current_user %}
        <div><a href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a></div>
        <div><button class="deleteBtn" data-post-id="{{ post.id }}" onclick="toggleModal()">Delete</button></div>
      {% endif %}
    </div>
  </div>
  <div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close" onclick="toggleModal()">&times;</span>
        <div class="btn-container">
          <p>Do you want to delete?</p>
          <div class="btn-delete">
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="Post">
              <input type="submit" class="button" value="Delete">
            </form>
            <button onclick="toggleModal()">No</button>
          </div>
        </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/review.html
{% extends 'base.html' %}
{% block content %}
<section class="section-form">
    <div class="form-container">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <h2>Describe Your Experience with this User</h2>
        <fieldset class="input-box">
            <div class="input-box">
                {{ form.content.label(class='form-check-label') }}
                {% if form.content.error %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class='form-control form-control-lg') }}
                {% endif %}
            </div>
            <div class="input-box">
                <label class="form-label">Rate us from 1 to 5 stars</label>
                <div class="stars" data-rating="{{ form.rating.data }}">  <i class="star fas fa-star" data-value="1"></i>
                  <i class="star fas fa-star" data-value="2"></i>
                  <i class="star fas fa-star" data-value="3"></i>
                  <i class="star fas fa-star" data-value="4"></i>
                  <i class="star fas fa-star" data-value="5"></i>
                </div>
                <input type="hidden" name="rating">
            </div>
        </fieldset>
        <div class="input-box">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    </div>
</section>
{% endblock %}